diff --git a//dev/null b/.github/workflows/auto-merge.yml
index 00000000..f4595f2f 100644
--- a//dev/null
++ b/.github/workflows/auto-merge.yml
@@ -0,0 +1,23 @@
name: Auto Merge Work into Main

on:
  push:
    branches:
      - work

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge work into main
        run: |
          git fetch origin
          git checkout main
       git merge --ff-only origin/work
       git push origin main
